### ISSUE TITLE
[問題回報] macOS 版本 Menu Bar 圖標黑影

### ISSUE THREAD

**Issue by Nanporo** [ExpTechTW/TREM-tauri#37]
### ✍🏻 描述詳細情況
* 預期效果: Menu Bar 左上不應該有黑影
* 實際效果: 疑似 Menu Bar 圖示錯誤

### 📑 相關資訊
* 版本: v0.0.0-alpha.2 (macOS 14.3.1)

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: 開啟程式後可立即復現此錯誤，過一段時間後消失。
黑影點擊後會開啟右邊正確圖標位置的Menu。

####  此檔案由 ExpTech.tw 設計製作

![QQ20240215-234104](https://github.com/ExpTechTW/TREM-tauri/assets/15816531/79489cca-c73f-4bcd-96f9-e433abefbaf8)
![QQ20240215-234240](https://github.com/ExpTechTW/TREM-tauri/assets/15816531/f2f82c6c-7961-45dc-ad11-73a638971fe4)

**Comment by kamiya10** [comment]
fixed in https://github.com/ExpTechTW/TREM-tauri/commit/00dbb1108fc536e49428acff4eda1287e897fb70#diff-fa09f1dac39604a735cd6a53957d3c35e0c3298cca9cf4829180f167abbd69b7
