### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xiaobala** [ExpTechTW/TREM-tauri#61]
### 描述詳細情況

點選設定沒東西

### 問題重現步驟

點選設定沒東西

### 截圖或影片

![319951137-d0a9340c-812c-44b0-a813-ebc06f8068af](https://github.com/ExpTechTW/TREM-tauri/assets/166120884/b10f731f-9459-4c19-880d-472af7ebbc96)

### 程式版本

v0.0.0

### 記錄檔

![Uploading 319951137-d0a9340c-812c-44b0-a813-ebc06f8068af.png…]()

**Comment by Kawaharu869** [comment]
![image](https://github.com/ExpTechTW/TREM-tauri/assets/116153360/05c5a020-7f27-4fd9-b0bf-aaab097348e1)

**Comment by kamiya10** [comment]
duplicate of #59
