### ISSUE TITLE
[Bug]: 無法打開設定介面

### ISSUE THREAD

**Issue by hanhan3c** [ExpTechTW/TREM-tauri#71]
### 描述詳細情況

無法打開設定介面
在Windows和Mac都是一樣的狀況。

https://github.com/ExpTechTW/TREM-tauri/assets/140958031/460aa197-a21f-4c0d-b9b1-7a1cdfafb9a3

![螢幕擷取畫面 2024-04-24 213857](https://github.com/ExpTechTW/TREM-tauri/assets/140958031/56876315-a322-4266-add7-35ef954ac7b6)

### 問題重現步驟

開啟TREM Tauri，然後選擇設定。

https://github.com/ExpTechTW/TREM-tauri/assets/140958031/be7fe281-e03c-4b3d-9b99-c840567e66fe

### 截圖或影片

https://github.com/ExpTechTW/TREM-tauri/assets/140958031/56915573-4b61-40b3-ab7f-78aac7a0c2f6

![螢幕擷取畫面 2024-04-24 213857](https://github.com/ExpTechTW/TREM-tauri/assets/140958031/546a7f8a-5b57-4039-a80e-d4e3ba3d2d77)

### 程式版本

v0.0.0-alpha.4

### 記錄檔

很抱歉，我無法點選設定，因此沒有記錄檔。

**Comment by kamiya10** [comment]
duplicate of #59
