### ISSUE TITLE
[Bug]: Config裡的設定問題

### ISSUE THREAD

**Issue by hanhan3ctw** [ExpTechTW/TREM-tauri#74]
### 描述詳細情況

我希望可以在Trem Tauri中顯示附近測站的資訊，我在config中的location station中填入了SE-Net 11366796，可是軟體內重新整理後仍顯示載入中，請問我的測站id填入的格式是否有錯誤。此外，有辦法可以在主業中顯示最近的地震報告嗎?以上兩個問題建議可以在設定檔的教學中提供更詳細的教學，才能在暫時沒有設定介面的情況下讓我們更簡單的設置。

### 問題重現步驟

打開config設定檔

### 截圖或影片

![image](https://github.com/ExpTechTW/TREM-tauri/assets/143109538/40179e7d-209c-4cd3-8998-38729982b841)
![image](https://github.com/ExpTechTW/TREM-tauri/assets/143109538/53bffee3-9286-4f07-9363-46b659c583d1)

### 程式版本

v0.0.0-alpha.4

### 記錄檔

在沒有設定介面的情況下，我不知道如何取得記錄檔。

**Comment by kamiya10** [comment]
station 只需要填 SID  `11366796` 就好
不需要連測站的種類都填進去
之後的版本會做成選單
