### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RayHuang1234** [ExpTechTW/TREM-tauri#76]
### 描述詳細情況

我用Mac然後打開地震報告跟設定都沒有用處 就是台灣地圖而已

### 問題重現步驟

修改ＭAC版上列錯誤

### 程式版本

TRem Tauri.v0.0.0-alpha4{Macos}

### 記錄檔

用不了 所以沒有

**Comment by kamiya4047** [comment]
duplicate of #59
