### ISSUE TITLE
[Bug]:  後端API request過於頻繁

### ISSUE THREAD

**Issue by EXCurryBar** [ExpTechTW/TREM-tauri#78]
### 描述詳細情況

一小時內連線數過多

## 無法復現
目前因連線數過多遭蔽校計算機與網路中心封鎖外網

     1. 發現網路遭封鎖
     2. 確認封鎖時間約2024/06/12 19:31:34
     3. 檢查DNS record 發現大量p2p-*.exptech.com.tw連線

### 截圖或影片
![image](https://github.com/ExpTechTW/TREM-tauri/assets/51626988/6351e618-54cc-40a4-b22e-e57f008798f8)
![image](https://github.com/ExpTechTW/TREM-tauri/assets/51626988/d1542d8e-cbe5-4993-b402-b02dcb9ced4d)
![image](https://github.com/ExpTechTW/TREM-tauri/assets/51626988/eabad9a3-40c0-42a2-a51b-af399b063442)
![image](https://github.com/ExpTechTW/TREM-tauri/assets/51626988/ce7221ae-5ad1-48aa-8b5f-a82313a8c173)
![image](https://github.com/ExpTechTW/TREM-tauri/assets/51626988/6b7637dc-4690-409d-ac91-fc390cee549f)
![image](https://github.com/ExpTechTW/TREM-tauri/assets/51626988/0ab886ae-6bff-4c80-bec4-2b7dc3fc1bc5)

### 程式版本

v0.0.0-alpha.4

### 記錄檔

於4/29關閉後記錄檔斷掉，但程式仍在背景執行

**Comment by kamiya4047** [comment]
tauri 版本沒有實裝 p2p 連線功能
你的 issue 應該是開錯地方了
